In [25]:
# optimal rotation and translation
import numpy as np
import numpy.linalg as la

O = np.array([[1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]]).T

O_centroid = (O[0]+O[1]+O[2])/3.0
print(O_centroid)

A = np.array([[0.85287691, 0.49239115, 0.17364311],
    [-0.46627858,  0.86795247, -0.17100523],
    [-0.23491543,  0.06488035,  0.96984807]]).T
print(np.dot(A.T[0],A.T[1]))
print(np.dot(A.T[1],A.T[2]))
print(np.dot(A.T[0],A.T[2]))

print(((0.85287691-0.46627858) + np.sqrt((0.85287691-0.46627858)**2 -4*(0.85287691)*(-0.46627858)))/2)

A_centroid = (A[0]+A[1]+A[2])/3.0
print(A_centroid)

H = np.matmul((A - np.array([A_centroid,A_centroid,A_centroid]).T),(O - np.array([O_centroid,O_centroid,O_centroid]).T).T)
print(H)
U,S,VH = la.svd(H)
print(np.matmul(VH,U))

[0.33333333 0.33333333 0.33333333]
3.7558738064102926e-10
8.820477959137207e-10
-7.98521110345618e-10
0.85287691
[0.50630372 0.07688955 0.26660433]
[[ 0.80231594 -0.51683955 -0.2854764 ]
 [ 0.01731649  0.39287781 -0.41019431]
 [-0.15051887 -0.49516721  0.64568609]]
[[ 0.93449024 -0.01693393  0.35558576]
 [ 0.16448431  0.90638961 -0.38910512]
 [-0.31571016  0.42210321  0.84979761]]
